Implement CLI args in helper scripts.
Lots of refactoring for code clarity.

diff --git a/scripts/new_client b/scripts/new_client
--- a/scripts/new_client
+++ b/scripts/new_client
@@ -1,2 +1,44 @@
 #!/bin/bash
-sudo docker run -e CLIENT_NAME=$1 -v /etc/openvpn:/etc/openvpn:rw -privileged symmetric/dockvpn new_client
+usage() {
+    echo "Usage: $0 -c CLIENT_NAME [-i <EXT_IP] [-p EXT_PORT] [-d CA_DIR]" >&2
+}
+
+CA_DIR="/etc/openvpn"
+
+while getopts ":c:i:p:d:h" o; do
+    case "${o}" in
+        c)
+            CLIENT_NAME=$OPTARG
+            echo "Got CLIENT_NAME=$CLIENT_NAME"
+            ;;
+        i)
+            EXT_IP=$OPTARG
+            echo "Got EXT_IP=$EXT_IP"
+            ;;
+        p)
+            EXT_PORT=$OPTARG
+            echo "Got EXT_PORT=$EXT_PORT"
+            ;;
+        d)
+            CA_DIR=$OPTARG
+            echo "Got CA_DIR=$CA_DIR"
+            ;;
+        h)
+            usage
+            exit 0
+            ;;
+        \?)
+            echo "Invalid option $OPTARG"
+            usage
+            exit 1
+            ;;
+    esac
+done
+
+[ "$CLIENT_NAME" ] || {
+    echo "Must specify client name with the -c flag."
+    exit 1
+}
+
+sudo docker run -e CLIENT_NAME=$CLIENT_NAME -e EXT_IP=$EXT_IP -e EXT_PORT=$EXT_PORT -v $CA_DIR:/etc/openvpn:rw -privileged symmetric/dockvpn new_client
+
diff --git a/scripts/start b/scripts/start
--- a/scripts/start
+++ b/scripts/start
@@ -1,2 +1,37 @@
 #!/bin/bash
-sudo docker run -d -v /etc/openvpn:/etc/openvpn:rw -privileged -p 443:443/tcp symmetric/dockvpn
+usage() {
+    echo "Usage: $0 [-i <LOCAL_IP] [-p LOCAL_PORT] [-d CA_DIR]" >&2
+}
+
+LOCAL_PORT=443
+CA_DIR="/etc/openvpn"
+
+# add :i:p: in production
+while getopts ":i:p:d:h" o; do
+    case "${o}" in
+        i)
+            LOCAL_IP=$OPTARG
+            echo "Got LOCAL_IP=$LOCAL_IP"
+            ;;
+        p)
+            LOCAL_PORT=$OPTARG
+            echo "Got LOCAL_PORT=$LOCAL_PORT"
+            ;;
+        d)
+            CA_DIR=$OPTARG
+            echo "Got CA_DIR=$CA_DIR"
+            ;;
+        h)
+            usage
+            exit 0
+            ;;
+        \?)
+            echo "Invalid option $OPTARG"
+            usage
+            exit 1
+            ;;
+    esac
+done
+
+sudo docker run -e LOCAL_IP=$LOCAL_IP -e LOCAL_PORT=$LOCAL_PORT -d -v $CA_DIR:/etc/openvpn:rw -privileged -p $LOCAL_PORT:$LOCAL_PORT/tcp symmetric/dockvpn
+
